name: Automated testing
on:
  push:
    branches:
      - master
jobs:
  AutomatedTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: apt-get install libbrotli-dev
      - run: make ftest
      - run: ./ftest